# Generated by Django 3.1.1 on 2020-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='description',
            field=models.CharField(default='unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movieLib.Actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='unknown', max_length=20000),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
