# Generated by Django 3.1.1 on 2020-09-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLib', '0003_auto_20200908_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
