# Generated by Django 3.1.1 on 2020-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLib', '0004_auto_20200908_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='actor',
            name='imagePath',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imagePath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
