# Generated by Django 3.1.1 on 2020-09-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieLib', '0005_auto_20200908_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imagePath',
            field=models.CharField(default='/static/image/404/movie.jpg', max_length=200),
        ),
    ]
