# Generated by Django 3.1.1 on 2020-09-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieLib', '0007_auto_20200908_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieLib.movie')),
            ],
        ),
    ]
